global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Apunta a sí mismo

  - job_name: 'node-exporter' # Apunta a la IP del HOST donde corre el exporter
    static_configs:
      - targets: ['192.168.1.143:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'apache-exporter' # Usar el exporter dedicado
    static_configs:
      - targets: ['apache-exporter:9117']

