global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.30.8.94:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['10.30.8.94:8080']

  - job_name: 'apache'
    static_configs:
      - targets: ['10.30.8.94:9117']
