{
    "apiVersion": 1,
    "datasources": [
        {
            "access": "proxy",
            "editable": true,
            "name": "DS_PROMETHEUS", # Changed name here
            "orgId": 1,
            "type": "prometheus",
            "url": "http://prometheus:9090",
            "version": 1,
            "isDefault": true
        }
    ]
}
